### ISSUE TITLE
Error: invalid configuration location

### ISSUE THREAD

**Issue by FherStk** [anrouxel/modelio-snapcraft#3]
Dear Antonin,

When starts, I get an "invalid configuration location" error that says: "The configuration area at '/home/<user>/.modelio/5.4/opensource-cache/conf' could not be created. Please choose a writable location using the '-configuration' command line option.":
![imagen](https://github.com/user-attachments/assets/e67695ea-de82-4159-a76b-cbaec7f66268)

I tried creating the folder manually but then I get a generic error message:
![imagen](https://github.com/user-attachments/assets/fb8342be-dfb1-4994-9ef1-b03081b1f5b5)

This is the terminal output in the second case (with the folders created):
![imagen](https://github.com/user-attachments/assets/e0b301f7-c8e5-4888-a3cf-be28af6d8c8c)

I guess that the snap is trying to access a hidden user folder, but no "persona-files" interface/plug with write permissions has been setup: https://snapcraft.io/docs/personal-files-interface

Tested on Ubuntu 24.04 and on Linux Mint 22.

Thanks in advance,
Fher

**Comment by anrouxel** [comment]
Dear Fher,
I have just updated the snapcraft.yaml file by changing it from `-Duser.home=$HOME` to `-Duser.home=$SNAP_USER_DATA` and testing in an Ubuntu 24.04 virtual machine (LXC/LXD) the application starts. Could you please confirm that it works for you?

#11 
```bash
snap refresh modelio --channel latest/edge
```

Best regards,
anrouxel

**Comment by anrouxel** [comment]
The following screenshots were taken during automated testing:

  ![window](https://raw.githubusercontent.com/anrouxel/ci-screenshots/main/20241023-modelio-11-window.png)

  ![screen](https://raw.githubusercontent.com/anrouxel/ci-screenshots/main/20241023-modelio-11-screen.png)

**Comment by FherStk** [comment]
> Dear Fher, I have just updated the snapcraft.yaml file by changing it from `-Duser.home=$HOME` to `-Duser.home=$SNAP_USER_DATA` and testing in an Ubuntu 24.04 virtual machine (LXC/LXD) the application starts. Could you please confirm that it works for you?
> 
> #11
> 
> ```shell
> snap refresh modelio --channel latest/edge
> ```
> 
> Best regards, anrouxel

Dear Antonin,

Now it works great, you saved my day!
Thanks a lot!
